### ISSUE TITLE
UnboundLocalError: local variable "hostnames referenced before assignment"

### ISSUE THREAD

**Issue by lamoni** [Juniper/contrail-fabric-utils#175]
Running into this issue on Ubuntu 14.04.2 on Python 2.7.6.  I had to modify cluster.py to get "setup_storage" command to work while installing the Contrail Storage solution.

Added this line to the top of get_all_hostnames() function:

```
hostnames = []
```

Once added, the command executes and Contrail storage is installed correctly.

**Comment by cijohnson** [comment]
Fixed this issue in commit https://github.com/Juniper/contrail-fabric-utils/commit/dbe38cc4f1e770f17b1b84199f8a28d6ae316d3e

**Comment by lamoni** [comment]
Excellent, thanks
